name: study
description: "Example app for using clean architecture with flutter and firebase with bloc pattern"

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  bloc: ^8.1.4
  cloud_firestore: ^4.15.10
  equatable: ^2.0.5
  firebase_auth: ^4.18.0
  firebase_core: ^2.27.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_native_splash: ^2.4.0
  fpdart: ^1.1.0
  gap: ^3.0.1
  get_it: ^7.6.7
  go_router: ^13.2.2
  injectable: ^2.3.2  
  json_annotation: ^4.8.1
  logger: ^2.2.0
  url_strategy: ^0.2.0

  
  
  



dev_dependencies:
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.1
  json_serializable: ^6.7.1
  very_good_analysis: ^5.1.0
  
 
  
  

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_native_splash:
  color: "#000000"
  android: true
  ios: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  min_sdk_android: 21 
  image_path: "assets/images/app_icon.jpeg"
  web:
    generate: true
    background_color: "#000000"
    theme_color: "#000000"
